<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>Emoji list - EmojiSymbols Font</title>
<meta name="description" content="EmojiSymbols font of Unicode6.0, free download." />
<link rel="stylesheet" href="css/reset.css" media="all" />
<link rel="stylesheet" href="css/style.css" media="all" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5604895-34']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<body>
<div class="header"><div class="hwrap">
<ul>
<li class="g01"><a href="http://emojisymbols.com/">Home</a></li>
<li class="g02"><a href="emojilist.php">Emoji list</a></li>
<li class="g03"><a href="faq.php">FAQ</a></li>
<li class="g04"><a href="beforeuse.php">Before use</a></li>
<li class="g05"><a href="inquiry.php">Inquiry</a></li>
</ul>
<p class="h_dl"><a href="beforeuse.php">Download Page</a></p>
<!-- /header --></div></div>


<div class="cwrap cf">
<h1 class="logo"><a href="http://emojisymbols.com/"><img src="img/logo.png" alt="EmojiSymbols Font" /></a></h1>


<div class="emoji_list cf">
<dl><dt><span class="emj">&#x1F520;</span></dt><dd><input type="text" value="&amp;#x1F520;" /><dd></dl>
<dl><dt><span class="emj">&#x1F521;</span></dt><dd><input type="text" value="&amp;#x1F521;" /><dd></dl>
<dl><dt><span class="emj">&#x1F524;</span></dt><dd><input type="text" value="&amp;#x1F524;" /><dd></dl>
<dl><dt><span class="emj">&#x1F300;</span></dt><dd><input type="text" value="&amp;#x1F300;" /><dd></dl>
<dl><dt><span class="emj">&#x1F301;</span></dt><dd><input type="text" value="&amp;#x1F301;" /><dd></dl>
<dl><dt><span class="emj">&#x1F302;</span></dt><dd><input type="text" value="&amp;#x1F302;" /><dd></dl>
<dl><dt><span class="emj">&#x1F303;</span></dt><dd><input type="text" value="&amp;#x1F303;" /><dd></dl>
<dl><dt><span class="emj">&#x1F304;</span></dt><dd><input type="text" value="&amp;#x1F304;" /><dd></dl>
<dl><dt><span class="emj">&#x1F305;</span></dt><dd><input type="text" value="&amp;#x1F305;" /><dd></dl>
<dl><dt><span class="emj">&#x1F306;</span></dt><dd><input type="text" value="&amp;#x1F306;" /><dd></dl>
<dl><dt><span class="emj">&#x1F307;</span></dt><dd><input type="text" value="&amp;#x1F307;" /><dd></dl>
<dl><dt><span class="emj">&#x1F308;</span></dt><dd><input type="text" value="&amp;#x1F308;" /><dd></dl>
<dl><dt><span class="emj">&#x1F309;</span></dt><dd><input type="text" value="&amp;#x1F309;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30A;</span></dt><dd><input type="text" value="&amp;#x1F30A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30B;</span></dt><dd><input type="text" value="&amp;#x1F30B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30C;</span></dt><dd><input type="text" value="&amp;#x1F30C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30D;</span></dt><dd><input type="text" value="&amp;#x1F30D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30E;</span></dt><dd><input type="text" value="&amp;#x1F30E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F30F;</span></dt><dd><input type="text" value="&amp;#x1F30F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F310;</span></dt><dd><input type="text" value="&amp;#x1F310;" /><dd></dl>
<dl><dt><span class="emj">&#x1F311;</span></dt><dd><input type="text" value="&amp;#x1F311;" /><dd></dl>
<dl><dt><span class="emj">&#x1F312;</span></dt><dd><input type="text" value="&amp;#x1F312;" /><dd></dl>
<dl><dt><span class="emj">&#x1F313;</span></dt><dd><input type="text" value="&amp;#x1F313;" /><dd></dl>
<dl><dt><span class="emj">&#x1F314;</span></dt><dd><input type="text" value="&amp;#x1F314;" /><dd></dl>
<dl><dt><span class="emj">&#x1F315;</span></dt><dd><input type="text" value="&amp;#x1F315;" /><dd></dl>
<dl><dt><span class="emj">&#x1F316;</span></dt><dd><input type="text" value="&amp;#x1F316;" /><dd></dl>
<dl><dt><span class="emj">&#x1F317;</span></dt><dd><input type="text" value="&amp;#x1F317;" /><dd></dl>
<dl><dt><span class="emj">&#x1F318;</span></dt><dd><input type="text" value="&amp;#x1F318;" /><dd></dl>
<dl><dt><span class="emj">&#x1F319;</span></dt><dd><input type="text" value="&amp;#x1F319;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31A;</span></dt><dd><input type="text" value="&amp;#x1F31A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31B;</span></dt><dd><input type="text" value="&amp;#x1F31B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31C;</span></dt><dd><input type="text" value="&amp;#x1F31C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31D;</span></dt><dd><input type="text" value="&amp;#x1F31D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31E;</span></dt><dd><input type="text" value="&amp;#x1F31E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F31F;</span></dt><dd><input type="text" value="&amp;#x1F31F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F320;</span></dt><dd><input type="text" value="&amp;#x1F320;" /><dd></dl>
<dl><dt><span class="emj">&#x1F330;</span></dt><dd><input type="text" value="&amp;#x1F330;" /><dd></dl>
<dl><dt><span class="emj">&#x1F331;</span></dt><dd><input type="text" value="&amp;#x1F331;" /><dd></dl>
<dl><dt><span class="emj">&#x1F332;</span></dt><dd><input type="text" value="&amp;#x1F332;" /><dd></dl>
<dl><dt><span class="emj">&#x1F333;</span></dt><dd><input type="text" value="&amp;#x1F333;" /><dd></dl>
<dl><dt><span class="emj">&#x1F334;</span></dt><dd><input type="text" value="&amp;#x1F334;" /><dd></dl>
<dl><dt><span class="emj">&#x1F335;</span></dt><dd><input type="text" value="&amp;#x1F335;" /><dd></dl>
<dl><dt><span class="emj">&#x1F337;</span></dt><dd><input type="text" value="&amp;#x1F337;" /><dd></dl>
<dl><dt><span class="emj">&#x1F338;</span></dt><dd><input type="text" value="&amp;#x1F338;" /><dd></dl>
<dl><dt><span class="emj">&#x1F339;</span></dt><dd><input type="text" value="&amp;#x1F339;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33A;</span></dt><dd><input type="text" value="&amp;#x1F33A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33B;</span></dt><dd><input type="text" value="&amp;#x1F33B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33C;</span></dt><dd><input type="text" value="&amp;#x1F33C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33D;</span></dt><dd><input type="text" value="&amp;#x1F33D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33E;</span></dt><dd><input type="text" value="&amp;#x1F33E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F33F;</span></dt><dd><input type="text" value="&amp;#x1F33F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F340;</span></dt><dd><input type="text" value="&amp;#x1F340;" /><dd></dl>
<dl><dt><span class="emj">&#x1F341;</span></dt><dd><input type="text" value="&amp;#x1F341;" /><dd></dl>
<dl><dt><span class="emj">&#x1F342;</span></dt><dd><input type="text" value="&amp;#x1F342;" /><dd></dl>
<dl><dt><span class="emj">&#x1F343;</span></dt><dd><input type="text" value="&amp;#x1F343;" /><dd></dl>
<dl><dt><span class="emj">&#x1F344;</span></dt><dd><input type="text" value="&amp;#x1F344;" /><dd></dl>
<dl><dt><span class="emj">&#x1F345;</span></dt><dd><input type="text" value="&amp;#x1F345;" /><dd></dl>
<dl><dt><span class="emj">&#x1F346;</span></dt><dd><input type="text" value="&amp;#x1F346;" /><dd></dl>
<dl><dt><span class="emj">&#x1F347;</span></dt><dd><input type="text" value="&amp;#x1F347;" /><dd></dl>
<dl><dt><span class="emj">&#x1F348;</span></dt><dd><input type="text" value="&amp;#x1F348;" /><dd></dl>
<dl><dt><span class="emj">&#x1F349;</span></dt><dd><input type="text" value="&amp;#x1F349;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34A;</span></dt><dd><input type="text" value="&amp;#x1F34A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34B;</span></dt><dd><input type="text" value="&amp;#x1F34B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34C;</span></dt><dd><input type="text" value="&amp;#x1F34C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34D;</span></dt><dd><input type="text" value="&amp;#x1F34D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34E;</span></dt><dd><input type="text" value="&amp;#x1F34E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F34F;</span></dt><dd><input type="text" value="&amp;#x1F34F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F350;</span></dt><dd><input type="text" value="&amp;#x1F350;" /><dd></dl>
<dl><dt><span class="emj">&#x1F351;</span></dt><dd><input type="text" value="&amp;#x1F351;" /><dd></dl>
<dl><dt><span class="emj">&#x1F352;</span></dt><dd><input type="text" value="&amp;#x1F352;" /><dd></dl>
<dl><dt><span class="emj">&#x1F353;</span></dt><dd><input type="text" value="&amp;#x1F353;" /><dd></dl>
<dl><dt><span class="emj">&#x1F354;</span></dt><dd><input type="text" value="&amp;#x1F354;" /><dd></dl>
<dl><dt><span class="emj">&#x1F355;</span></dt><dd><input type="text" value="&amp;#x1F355;" /><dd></dl>
<dl><dt><span class="emj">&#x1F356;</span></dt><dd><input type="text" value="&amp;#x1F356;" /><dd></dl>
<dl><dt><span class="emj">&#x1F357;</span></dt><dd><input type="text" value="&amp;#x1F357;" /><dd></dl>
<dl><dt><span class="emj">&#x1F358;</span></dt><dd><input type="text" value="&amp;#x1F358;" /><dd></dl>
<dl><dt><span class="emj">&#x1F359;</span></dt><dd><input type="text" value="&amp;#x1F359;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35A;</span></dt><dd><input type="text" value="&amp;#x1F35A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35B;</span></dt><dd><input type="text" value="&amp;#x1F35B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35C;</span></dt><dd><input type="text" value="&amp;#x1F35C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35D;</span></dt><dd><input type="text" value="&amp;#x1F35D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35E;</span></dt><dd><input type="text" value="&amp;#x1F35E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F35F;</span></dt><dd><input type="text" value="&amp;#x1F35F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F360;</span></dt><dd><input type="text" value="&amp;#x1F360;" /><dd></dl>
<dl><dt><span class="emj">&#x1F361;</span></dt><dd><input type="text" value="&amp;#x1F361;" /><dd></dl>
<dl><dt><span class="emj">&#x1F362;</span></dt><dd><input type="text" value="&amp;#x1F362;" /><dd></dl>
<dl><dt><span class="emj">&#x1F363;</span></dt><dd><input type="text" value="&amp;#x1F363;" /><dd></dl>
<dl><dt><span class="emj">&#x1F364;</span></dt><dd><input type="text" value="&amp;#x1F364;" /><dd></dl>
<dl><dt><span class="emj">&#x1F365;</span></dt><dd><input type="text" value="&amp;#x1F365;" /><dd></dl>
<dl><dt><span class="emj">&#x1F366;</span></dt><dd><input type="text" value="&amp;#x1F366;" /><dd></dl>
<dl><dt><span class="emj">&#x1F367;</span></dt><dd><input type="text" value="&amp;#x1F367;" /><dd></dl>
<dl><dt><span class="emj">&#x1F368;</span></dt><dd><input type="text" value="&amp;#x1F368;" /><dd></dl>
<dl><dt><span class="emj">&#x1F369;</span></dt><dd><input type="text" value="&amp;#x1F369;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36A;</span></dt><dd><input type="text" value="&amp;#x1F36A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36B;</span></dt><dd><input type="text" value="&amp;#x1F36B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36C;</span></dt><dd><input type="text" value="&amp;#x1F36C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36D;</span></dt><dd><input type="text" value="&amp;#x1F36D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36E;</span></dt><dd><input type="text" value="&amp;#x1F36E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F36F;</span></dt><dd><input type="text" value="&amp;#x1F36F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F370;</span></dt><dd><input type="text" value="&amp;#x1F370;" /><dd></dl>
<dl><dt><span class="emj">&#x1F371;</span></dt><dd><input type="text" value="&amp;#x1F371;" /><dd></dl>
<dl><dt><span class="emj">&#x1F372;</span></dt><dd><input type="text" value="&amp;#x1F372;" /><dd></dl>
<dl><dt><span class="emj">&#x1F373;</span></dt><dd><input type="text" value="&amp;#x1F373;" /><dd></dl>
<dl><dt><span class="emj">&#x1F374;</span></dt><dd><input type="text" value="&amp;#x1F374;" /><dd></dl>
<dl><dt><span class="emj">&#x1F375;</span></dt><dd><input type="text" value="&amp;#x1F375;" /><dd></dl>
<dl><dt><span class="emj">&#x1F376;</span></dt><dd><input type="text" value="&amp;#x1F376;" /><dd></dl>
<dl><dt><span class="emj">&#x1F377;</span></dt><dd><input type="text" value="&amp;#x1F377;" /><dd></dl>
<dl><dt><span class="emj">&#x1F378;</span></dt><dd><input type="text" value="&amp;#x1F378;" /><dd></dl>
<dl><dt><span class="emj">&#x1F379;</span></dt><dd><input type="text" value="&amp;#x1F379;" /><dd></dl>
<dl><dt><span class="emj">&#x1F37A;</span></dt><dd><input type="text" value="&amp;#x1F37A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F37B;</span></dt><dd><input type="text" value="&amp;#x1F37B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F37C;</span></dt><dd><input type="text" value="&amp;#x1F37C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F380;</span></dt><dd><input type="text" value="&amp;#x1F380;" /><dd></dl>
<dl><dt><span class="emj">&#x1F381;</span></dt><dd><input type="text" value="&amp;#x1F381;" /><dd></dl>
<dl><dt><span class="emj">&#x1F382;</span></dt><dd><input type="text" value="&amp;#x1F382;" /><dd></dl>
<dl><dt><span class="emj">&#x1F383;</span></dt><dd><input type="text" value="&amp;#x1F383;" /><dd></dl>
<dl><dt><span class="emj">&#x1F384;</span></dt><dd><input type="text" value="&amp;#x1F384;" /><dd></dl>
<dl><dt><span class="emj">&#x1F385;</span></dt><dd><input type="text" value="&amp;#x1F385;" /><dd></dl>
<dl><dt><span class="emj">&#x1F386;</span></dt><dd><input type="text" value="&amp;#x1F386;" /><dd></dl>
<dl><dt><span class="emj">&#x1F387;</span></dt><dd><input type="text" value="&amp;#x1F387;" /><dd></dl>
<dl><dt><span class="emj">&#x1F388;</span></dt><dd><input type="text" value="&amp;#x1F388;" /><dd></dl>
<dl><dt><span class="emj">&#x1F389;</span></dt><dd><input type="text" value="&amp;#x1F389;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38A;</span></dt><dd><input type="text" value="&amp;#x1F38A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38B;</span></dt><dd><input type="text" value="&amp;#x1F38B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38C;</span></dt><dd><input type="text" value="&amp;#x1F38C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38D;</span></dt><dd><input type="text" value="&amp;#x1F38D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38E;</span></dt><dd><input type="text" value="&amp;#x1F38E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F38F;</span></dt><dd><input type="text" value="&amp;#x1F38F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F390;</span></dt><dd><input type="text" value="&amp;#x1F390;" /><dd></dl>
<dl><dt><span class="emj">&#x1F391;</span></dt><dd><input type="text" value="&amp;#x1F391;" /><dd></dl>
<dl><dt><span class="emj">&#x1F392;</span></dt><dd><input type="text" value="&amp;#x1F392;" /><dd></dl>
<dl><dt><span class="emj">&#x1F393;</span></dt><dd><input type="text" value="&amp;#x1F393;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A0;</span></dt><dd><input type="text" value="&amp;#x1F3A0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A1;</span></dt><dd><input type="text" value="&amp;#x1F3A1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A2;</span></dt><dd><input type="text" value="&amp;#x1F3A2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A3;</span></dt><dd><input type="text" value="&amp;#x1F3A3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A4;</span></dt><dd><input type="text" value="&amp;#x1F3A4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A5;</span></dt><dd><input type="text" value="&amp;#x1F3A5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A6;</span></dt><dd><input type="text" value="&amp;#x1F3A6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A7;</span></dt><dd><input type="text" value="&amp;#x1F3A7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A8;</span></dt><dd><input type="text" value="&amp;#x1F3A8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3A9;</span></dt><dd><input type="text" value="&amp;#x1F3A9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AA;</span></dt><dd><input type="text" value="&amp;#x1F3AA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AB;</span></dt><dd><input type="text" value="&amp;#x1F3AB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AC;</span></dt><dd><input type="text" value="&amp;#x1F3AC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AD;</span></dt><dd><input type="text" value="&amp;#x1F3AD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AE;</span></dt><dd><input type="text" value="&amp;#x1F3AE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3AF;</span></dt><dd><input type="text" value="&amp;#x1F3AF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B0;</span></dt><dd><input type="text" value="&amp;#x1F3B0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B1;</span></dt><dd><input type="text" value="&amp;#x1F3B1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B2;</span></dt><dd><input type="text" value="&amp;#x1F3B2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B3;</span></dt><dd><input type="text" value="&amp;#x1F3B3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B4;</span></dt><dd><input type="text" value="&amp;#x1F3B4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B5;</span></dt><dd><input type="text" value="&amp;#x1F3B5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B6;</span></dt><dd><input type="text" value="&amp;#x1F3B6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B7;</span></dt><dd><input type="text" value="&amp;#x1F3B7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B8;</span></dt><dd><input type="text" value="&amp;#x1F3B8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3B9;</span></dt><dd><input type="text" value="&amp;#x1F3B9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BA;</span></dt><dd><input type="text" value="&amp;#x1F3BA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BB;</span></dt><dd><input type="text" value="&amp;#x1F3BB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BC;</span></dt><dd><input type="text" value="&amp;#x1F3BC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BD;</span></dt><dd><input type="text" value="&amp;#x1F3BD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BE;</span></dt><dd><input type="text" value="&amp;#x1F3BE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3BF;</span></dt><dd><input type="text" value="&amp;#x1F3BF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C0;</span></dt><dd><input type="text" value="&amp;#x1F3C0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C1;</span></dt><dd><input type="text" value="&amp;#x1F3C1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C2;</span></dt><dd><input type="text" value="&amp;#x1F3C2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C3;</span></dt><dd><input type="text" value="&amp;#x1F3C3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C4;</span></dt><dd><input type="text" value="&amp;#x1F3C4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C6;</span></dt><dd><input type="text" value="&amp;#x1F3C6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C7;</span></dt><dd><input type="text" value="&amp;#x1F3C7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C8;</span></dt><dd><input type="text" value="&amp;#x1F3C8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3C9;</span></dt><dd><input type="text" value="&amp;#x1F3C9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3CA;</span></dt><dd><input type="text" value="&amp;#x1F3CA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E0;</span></dt><dd><input type="text" value="&amp;#x1F3E0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E1;</span></dt><dd><input type="text" value="&amp;#x1F3E1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E2;</span></dt><dd><input type="text" value="&amp;#x1F3E2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E3;</span></dt><dd><input type="text" value="&amp;#x1F3E3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E4;</span></dt><dd><input type="text" value="&amp;#x1F3E4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E5;</span></dt><dd><input type="text" value="&amp;#x1F3E5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E6;</span></dt><dd><input type="text" value="&amp;#x1F3E6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E7;</span></dt><dd><input type="text" value="&amp;#x1F3E7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E8;</span></dt><dd><input type="text" value="&amp;#x1F3E8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3E9;</span></dt><dd><input type="text" value="&amp;#x1F3E9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3EA;</span></dt><dd><input type="text" value="&amp;#x1F3EA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3EB;</span></dt><dd><input type="text" value="&amp;#x1F3EB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3EC;</span></dt><dd><input type="text" value="&amp;#x1F3EC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3ED;</span></dt><dd><input type="text" value="&amp;#x1F3ED;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3EE;</span></dt><dd><input type="text" value="&amp;#x1F3EE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3EF;</span></dt><dd><input type="text" value="&amp;#x1F3EF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F3F0;</span></dt><dd><input type="text" value="&amp;#x1F3F0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F400;</span></dt><dd><input type="text" value="&amp;#x1F400;" /><dd></dl>
<dl><dt><span class="emj">&#x1F401;</span></dt><dd><input type="text" value="&amp;#x1F401;" /><dd></dl>
<dl><dt><span class="emj">&#x1F402;</span></dt><dd><input type="text" value="&amp;#x1F402;" /><dd></dl>
<dl><dt><span class="emj">&#x1F403;</span></dt><dd><input type="text" value="&amp;#x1F403;" /><dd></dl>
<dl><dt><span class="emj">&#x1F404;</span></dt><dd><input type="text" value="&amp;#x1F404;" /><dd></dl>
<dl><dt><span class="emj">&#x1F405;</span></dt><dd><input type="text" value="&amp;#x1F405;" /><dd></dl>
<dl><dt><span class="emj">&#x1F406;</span></dt><dd><input type="text" value="&amp;#x1F406;" /><dd></dl>
<dl><dt><span class="emj">&#x1F407;</span></dt><dd><input type="text" value="&amp;#x1F407;" /><dd></dl>
<dl><dt><span class="emj">&#x1F408;</span></dt><dd><input type="text" value="&amp;#x1F408;" /><dd></dl>
<dl><dt><span class="emj">&#x1F409;</span></dt><dd><input type="text" value="&amp;#x1F409;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40A;</span></dt><dd><input type="text" value="&amp;#x1F40A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40B;</span></dt><dd><input type="text" value="&amp;#x1F40B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40C;</span></dt><dd><input type="text" value="&amp;#x1F40C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40D;</span></dt><dd><input type="text" value="&amp;#x1F40D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40E;</span></dt><dd><input type="text" value="&amp;#x1F40E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F40F;</span></dt><dd><input type="text" value="&amp;#x1F40F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F410;</span></dt><dd><input type="text" value="&amp;#x1F410;" /><dd></dl>
<dl><dt><span class="emj">&#x1F411;</span></dt><dd><input type="text" value="&amp;#x1F411;" /><dd></dl>
<dl><dt><span class="emj">&#x1F412;</span></dt><dd><input type="text" value="&amp;#x1F412;" /><dd></dl>
<dl><dt><span class="emj">&#x1F413;</span></dt><dd><input type="text" value="&amp;#x1F413;" /><dd></dl>
<dl><dt><span class="emj">&#x1F414;</span></dt><dd><input type="text" value="&amp;#x1F414;" /><dd></dl>
<dl><dt><span class="emj">&#x1F415;</span></dt><dd><input type="text" value="&amp;#x1F415;" /><dd></dl>
<dl><dt><span class="emj">&#x1F416;</span></dt><dd><input type="text" value="&amp;#x1F416;" /><dd></dl>
<dl><dt><span class="emj">&#x1F417;</span></dt><dd><input type="text" value="&amp;#x1F417;" /><dd></dl>
<dl><dt><span class="emj">&#x1F418;</span></dt><dd><input type="text" value="&amp;#x1F418;" /><dd></dl>
<dl><dt><span class="emj">&#x1F419;</span></dt><dd><input type="text" value="&amp;#x1F419;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41A;</span></dt><dd><input type="text" value="&amp;#x1F41A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41B;</span></dt><dd><input type="text" value="&amp;#x1F41B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41C;</span></dt><dd><input type="text" value="&amp;#x1F41C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41D;</span></dt><dd><input type="text" value="&amp;#x1F41D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41E;</span></dt><dd><input type="text" value="&amp;#x1F41E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F41F;</span></dt><dd><input type="text" value="&amp;#x1F41F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F420;</span></dt><dd><input type="text" value="&amp;#x1F420;" /><dd></dl>
<dl><dt><span class="emj">&#x1F421;</span></dt><dd><input type="text" value="&amp;#x1F421;" /><dd></dl>
<dl><dt><span class="emj">&#x1F422;</span></dt><dd><input type="text" value="&amp;#x1F422;" /><dd></dl>
<dl><dt><span class="emj">&#x1F423;</span></dt><dd><input type="text" value="&amp;#x1F423;" /><dd></dl>
<dl><dt><span class="emj">&#x1F424;</span></dt><dd><input type="text" value="&amp;#x1F424;" /><dd></dl>
<dl><dt><span class="emj">&#x1F425;</span></dt><dd><input type="text" value="&amp;#x1F425;" /><dd></dl>
<dl><dt><span class="emj">&#x1F426;</span></dt><dd><input type="text" value="&amp;#x1F426;" /><dd></dl>
<dl><dt><span class="emj">&#x1F427;</span></dt><dd><input type="text" value="&amp;#x1F427;" /><dd></dl>
<dl><dt><span class="emj">&#x1F428;</span></dt><dd><input type="text" value="&amp;#x1F428;" /><dd></dl>
<dl><dt><span class="emj">&#x1F429;</span></dt><dd><input type="text" value="&amp;#x1F429;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42A;</span></dt><dd><input type="text" value="&amp;#x1F42A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42B;</span></dt><dd><input type="text" value="&amp;#x1F42B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42C;</span></dt><dd><input type="text" value="&amp;#x1F42C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42D;</span></dt><dd><input type="text" value="&amp;#x1F42D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42E;</span></dt><dd><input type="text" value="&amp;#x1F42E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F42F;</span></dt><dd><input type="text" value="&amp;#x1F42F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F430;</span></dt><dd><input type="text" value="&amp;#x1F430;" /><dd></dl>
<dl><dt><span class="emj">&#x1F431;</span></dt><dd><input type="text" value="&amp;#x1F431;" /><dd></dl>
<dl><dt><span class="emj">&#x1F432;</span></dt><dd><input type="text" value="&amp;#x1F432;" /><dd></dl>
<dl><dt><span class="emj">&#x1F433;</span></dt><dd><input type="text" value="&amp;#x1F433;" /><dd></dl>
<dl><dt><span class="emj">&#x1F434;</span></dt><dd><input type="text" value="&amp;#x1F434;" /><dd></dl>
<dl><dt><span class="emj">&#x1F435;</span></dt><dd><input type="text" value="&amp;#x1F435;" /><dd></dl>
<dl><dt><span class="emj">&#x1F436;</span></dt><dd><input type="text" value="&amp;#x1F436;" /><dd></dl>
<dl><dt><span class="emj">&#x1F437;</span></dt><dd><input type="text" value="&amp;#x1F437;" /><dd></dl>
<dl><dt><span class="emj">&#x1F438;</span></dt><dd><input type="text" value="&amp;#x1F438;" /><dd></dl>
<dl><dt><span class="emj">&#x1F439;</span></dt><dd><input type="text" value="&amp;#x1F439;" /><dd></dl>
<dl><dt><span class="emj">&#x1F43A;</span></dt><dd><input type="text" value="&amp;#x1F43A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F43B;</span></dt><dd><input type="text" value="&amp;#x1F43B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F43C;</span></dt><dd><input type="text" value="&amp;#x1F43C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F43D;</span></dt><dd><input type="text" value="&amp;#x1F43D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F43E;</span></dt><dd><input type="text" value="&amp;#x1F43E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F440;</span></dt><dd><input type="text" value="&amp;#x1F440;" /><dd></dl>
<dl><dt><span class="emj">&#x1F442;</span></dt><dd><input type="text" value="&amp;#x1F442;" /><dd></dl>
<dl><dt><span class="emj">&#x1F443;</span></dt><dd><input type="text" value="&amp;#x1F443;" /><dd></dl>
<dl><dt><span class="emj">&#x1F444;</span></dt><dd><input type="text" value="&amp;#x1F444;" /><dd></dl>
<dl><dt><span class="emj">&#x1F445;</span></dt><dd><input type="text" value="&amp;#x1F445;" /><dd></dl>
<dl><dt><span class="emj">&#x1F446;</span></dt><dd><input type="text" value="&amp;#x1F446;" /><dd></dl>
<dl><dt><span class="emj">&#x1F447;</span></dt><dd><input type="text" value="&amp;#x1F447;" /><dd></dl>
<dl><dt><span class="emj">&#x1F448;</span></dt><dd><input type="text" value="&amp;#x1F448;" /><dd></dl>
<dl><dt><span class="emj">&#x1F449;</span></dt><dd><input type="text" value="&amp;#x1F449;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44A;</span></dt><dd><input type="text" value="&amp;#x1F44A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44B;</span></dt><dd><input type="text" value="&amp;#x1F44B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44C;</span></dt><dd><input type="text" value="&amp;#x1F44C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44D;</span></dt><dd><input type="text" value="&amp;#x1F44D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44E;</span></dt><dd><input type="text" value="&amp;#x1F44E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F44F;</span></dt><dd><input type="text" value="&amp;#x1F44F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F450;</span></dt><dd><input type="text" value="&amp;#x1F450;" /><dd></dl>
<dl><dt><span class="emj">&#x1F451;</span></dt><dd><input type="text" value="&amp;#x1F451;" /><dd></dl>
<dl><dt><span class="emj">&#x1F452;</span></dt><dd><input type="text" value="&amp;#x1F452;" /><dd></dl>
<dl><dt><span class="emj">&#x1F453;</span></dt><dd><input type="text" value="&amp;#x1F453;" /><dd></dl>
<dl><dt><span class="emj">&#x1F454;</span></dt><dd><input type="text" value="&amp;#x1F454;" /><dd></dl>
<dl><dt><span class="emj">&#x1F455;</span></dt><dd><input type="text" value="&amp;#x1F455;" /><dd></dl>
<dl><dt><span class="emj">&#x1F456;</span></dt><dd><input type="text" value="&amp;#x1F456;" /><dd></dl>
<dl><dt><span class="emj">&#x1F457;</span></dt><dd><input type="text" value="&amp;#x1F457;" /><dd></dl>
<dl><dt><span class="emj">&#x1F458;</span></dt><dd><input type="text" value="&amp;#x1F458;" /><dd></dl>
<dl><dt><span class="emj">&#x1F459;</span></dt><dd><input type="text" value="&amp;#x1F459;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45A;</span></dt><dd><input type="text" value="&amp;#x1F45A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45B;</span></dt><dd><input type="text" value="&amp;#x1F45B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45C;</span></dt><dd><input type="text" value="&amp;#x1F45C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45D;</span></dt><dd><input type="text" value="&amp;#x1F45D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45E;</span></dt><dd><input type="text" value="&amp;#x1F45E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F45F;</span></dt><dd><input type="text" value="&amp;#x1F45F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F460;</span></dt><dd><input type="text" value="&amp;#x1F460;" /><dd></dl>
<dl><dt><span class="emj">&#x1F461;</span></dt><dd><input type="text" value="&amp;#x1F461;" /><dd></dl>
<dl><dt><span class="emj">&#x1F462;</span></dt><dd><input type="text" value="&amp;#x1F462;" /><dd></dl>
<dl><dt><span class="emj">&#x1F463;</span></dt><dd><input type="text" value="&amp;#x1F463;" /><dd></dl>
<dl><dt><span class="emj">&#x1F464;</span></dt><dd><input type="text" value="&amp;#x1F464;" /><dd></dl>
<dl><dt><span class="emj">&#x1F465;</span></dt><dd><input type="text" value="&amp;#x1F465;" /><dd></dl>
<dl><dt><span class="emj">&#x1F466;</span></dt><dd><input type="text" value="&amp;#x1F466;" /><dd></dl>
<dl><dt><span class="emj">&#x1F467;</span></dt><dd><input type="text" value="&amp;#x1F467;" /><dd></dl>
<dl><dt><span class="emj">&#x1F468;</span></dt><dd><input type="text" value="&amp;#x1F468;" /><dd></dl>
<dl><dt><span class="emj">&#x1F469;</span></dt><dd><input type="text" value="&amp;#x1F469;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46A;</span></dt><dd><input type="text" value="&amp;#x1F46A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46B;</span></dt><dd><input type="text" value="&amp;#x1F46B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46C;</span></dt><dd><input type="text" value="&amp;#x1F46C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46D;</span></dt><dd><input type="text" value="&amp;#x1F46D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46E;</span></dt><dd><input type="text" value="&amp;#x1F46E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F46F;</span></dt><dd><input type="text" value="&amp;#x1F46F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F470;</span></dt><dd><input type="text" value="&amp;#x1F470;" /><dd></dl>
<dl><dt><span class="emj">&#x1F471;</span></dt><dd><input type="text" value="&amp;#x1F471;" /><dd></dl>
<dl><dt><span class="emj">&#x1F472;</span></dt><dd><input type="text" value="&amp;#x1F472;" /><dd></dl>
<dl><dt><span class="emj">&#x1F473;</span></dt><dd><input type="text" value="&amp;#x1F473;" /><dd></dl>
<dl><dt><span class="emj">&#x1F474;</span></dt><dd><input type="text" value="&amp;#x1F474;" /><dd></dl>
<dl><dt><span class="emj">&#x1F475;</span></dt><dd><input type="text" value="&amp;#x1F475;" /><dd></dl>
<dl><dt><span class="emj">&#x1F476;</span></dt><dd><input type="text" value="&amp;#x1F476;" /><dd></dl>
<dl><dt><span class="emj">&#x1F477;</span></dt><dd><input type="text" value="&amp;#x1F477;" /><dd></dl>
<dl><dt><span class="emj">&#x1F478;</span></dt><dd><input type="text" value="&amp;#x1F478;" /><dd></dl>
<dl><dt><span class="emj">&#x1F479;</span></dt><dd><input type="text" value="&amp;#x1F479;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47A;</span></dt><dd><input type="text" value="&amp;#x1F47A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47B;</span></dt><dd><input type="text" value="&amp;#x1F47B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47C;</span></dt><dd><input type="text" value="&amp;#x1F47C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47D;</span></dt><dd><input type="text" value="&amp;#x1F47D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47E;</span></dt><dd><input type="text" value="&amp;#x1F47E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F47F;</span></dt><dd><input type="text" value="&amp;#x1F47F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F480;</span></dt><dd><input type="text" value="&amp;#x1F480;" /><dd></dl>
<dl><dt><span class="emj">&#x1F481;</span></dt><dd><input type="text" value="&amp;#x1F481;" /><dd></dl>
<dl><dt><span class="emj">&#x1F482;</span></dt><dd><input type="text" value="&amp;#x1F482;" /><dd></dl>
<dl><dt><span class="emj">&#x1F483;</span></dt><dd><input type="text" value="&amp;#x1F483;" /><dd></dl>
<dl><dt><span class="emj">&#x1F484;</span></dt><dd><input type="text" value="&amp;#x1F484;" /><dd></dl>
<dl><dt><span class="emj">&#x1F485;</span></dt><dd><input type="text" value="&amp;#x1F485;" /><dd></dl>
<dl><dt><span class="emj">&#x1F486;</span></dt><dd><input type="text" value="&amp;#x1F486;" /><dd></dl>
<dl><dt><span class="emj">&#x1F487;</span></dt><dd><input type="text" value="&amp;#x1F487;" /><dd></dl>
<dl><dt><span class="emj">&#x1F488;</span></dt><dd><input type="text" value="&amp;#x1F488;" /><dd></dl>
<dl><dt><span class="emj">&#x1F489;</span></dt><dd><input type="text" value="&amp;#x1F489;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48A;</span></dt><dd><input type="text" value="&amp;#x1F48A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48B;</span></dt><dd><input type="text" value="&amp;#x1F48B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48C;</span></dt><dd><input type="text" value="&amp;#x1F48C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48D;</span></dt><dd><input type="text" value="&amp;#x1F48D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48E;</span></dt><dd><input type="text" value="&amp;#x1F48E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F48F;</span></dt><dd><input type="text" value="&amp;#x1F48F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F490;</span></dt><dd><input type="text" value="&amp;#x1F490;" /><dd></dl>
<dl><dt><span class="emj">&#x1F491;</span></dt><dd><input type="text" value="&amp;#x1F491;" /><dd></dl>
<dl><dt><span class="emj">&#x1F492;</span></dt><dd><input type="text" value="&amp;#x1F492;" /><dd></dl>
<dl><dt><span class="emj">&#x1F493;</span></dt><dd><input type="text" value="&amp;#x1F493;" /><dd></dl>
<dl><dt><span class="emj">&#x1F494;</span></dt><dd><input type="text" value="&amp;#x1F494;" /><dd></dl>
<dl><dt><span class="emj">&#x1F495;</span></dt><dd><input type="text" value="&amp;#x1F495;" /><dd></dl>
<dl><dt><span class="emj">&#x1F496;</span></dt><dd><input type="text" value="&amp;#x1F496;" /><dd></dl>
<dl><dt><span class="emj">&#x1F497;</span></dt><dd><input type="text" value="&amp;#x1F497;" /><dd></dl>
<dl><dt><span class="emj">&#x1F498;</span></dt><dd><input type="text" value="&amp;#x1F498;" /><dd></dl>
<dl><dt><span class="emj">&#x1F499;</span></dt><dd><input type="text" value="&amp;#x1F499;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49A;</span></dt><dd><input type="text" value="&amp;#x1F49A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49B;</span></dt><dd><input type="text" value="&amp;#x1F49B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49C;</span></dt><dd><input type="text" value="&amp;#x1F49C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49D;</span></dt><dd><input type="text" value="&amp;#x1F49D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49E;</span></dt><dd><input type="text" value="&amp;#x1F49E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F49F;</span></dt><dd><input type="text" value="&amp;#x1F49F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A0;</span></dt><dd><input type="text" value="&amp;#x1F4A0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A1;</span></dt><dd><input type="text" value="&amp;#x1F4A1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A2;</span></dt><dd><input type="text" value="&amp;#x1F4A2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A3;</span></dt><dd><input type="text" value="&amp;#x1F4A3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A4;</span></dt><dd><input type="text" value="&amp;#x1F4A4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A5;</span></dt><dd><input type="text" value="&amp;#x1F4A5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A6;</span></dt><dd><input type="text" value="&amp;#x1F4A6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A7;</span></dt><dd><input type="text" value="&amp;#x1F4A7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A8;</span></dt><dd><input type="text" value="&amp;#x1F4A8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4A9;</span></dt><dd><input type="text" value="&amp;#x1F4A9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AA;</span></dt><dd><input type="text" value="&amp;#x1F4AA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AB;</span></dt><dd><input type="text" value="&amp;#x1F4AB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AC;</span></dt><dd><input type="text" value="&amp;#x1F4AC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AD;</span></dt><dd><input type="text" value="&amp;#x1F4AD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AE;</span></dt><dd><input type="text" value="&amp;#x1F4AE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4AF;</span></dt><dd><input type="text" value="&amp;#x1F4AF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B0;</span></dt><dd><input type="text" value="&amp;#x1F4B0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B1;</span></dt><dd><input type="text" value="&amp;#x1F4B1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B2;</span></dt><dd><input type="text" value="&amp;#x1F4B2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B3;</span></dt><dd><input type="text" value="&amp;#x1F4B3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B4;</span></dt><dd><input type="text" value="&amp;#x1F4B4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B5;</span></dt><dd><input type="text" value="&amp;#x1F4B5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B6;</span></dt><dd><input type="text" value="&amp;#x1F4B6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B7;</span></dt><dd><input type="text" value="&amp;#x1F4B7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B8;</span></dt><dd><input type="text" value="&amp;#x1F4B8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4B9;</span></dt><dd><input type="text" value="&amp;#x1F4B9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BA;</span></dt><dd><input type="text" value="&amp;#x1F4BA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BB;</span></dt><dd><input type="text" value="&amp;#x1F4BB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BC;</span></dt><dd><input type="text" value="&amp;#x1F4BC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BD;</span></dt><dd><input type="text" value="&amp;#x1F4BD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BE;</span></dt><dd><input type="text" value="&amp;#x1F4BE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4BF;</span></dt><dd><input type="text" value="&amp;#x1F4BF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C0;</span></dt><dd><input type="text" value="&amp;#x1F4C0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C1;</span></dt><dd><input type="text" value="&amp;#x1F4C1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C2;</span></dt><dd><input type="text" value="&amp;#x1F4C2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C3;</span></dt><dd><input type="text" value="&amp;#x1F4C3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C4;</span></dt><dd><input type="text" value="&amp;#x1F4C4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C5;</span></dt><dd><input type="text" value="&amp;#x1F4C5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C6;</span></dt><dd><input type="text" value="&amp;#x1F4C6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C7;</span></dt><dd><input type="text" value="&amp;#x1F4C7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C8;</span></dt><dd><input type="text" value="&amp;#x1F4C8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4C9;</span></dt><dd><input type="text" value="&amp;#x1F4C9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CA;</span></dt><dd><input type="text" value="&amp;#x1F4CA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CB;</span></dt><dd><input type="text" value="&amp;#x1F4CB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CC;</span></dt><dd><input type="text" value="&amp;#x1F4CC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CD;</span></dt><dd><input type="text" value="&amp;#x1F4CD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CE;</span></dt><dd><input type="text" value="&amp;#x1F4CE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4CF;</span></dt><dd><input type="text" value="&amp;#x1F4CF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D0;</span></dt><dd><input type="text" value="&amp;#x1F4D0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D1;</span></dt><dd><input type="text" value="&amp;#x1F4D1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D2;</span></dt><dd><input type="text" value="&amp;#x1F4D2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D3;</span></dt><dd><input type="text" value="&amp;#x1F4D3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D4;</span></dt><dd><input type="text" value="&amp;#x1F4D4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D5;</span></dt><dd><input type="text" value="&amp;#x1F4D5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D6;</span></dt><dd><input type="text" value="&amp;#x1F4D6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D7;</span></dt><dd><input type="text" value="&amp;#x1F4D7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D8;</span></dt><dd><input type="text" value="&amp;#x1F4D8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4D9;</span></dt><dd><input type="text" value="&amp;#x1F4D9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DA;</span></dt><dd><input type="text" value="&amp;#x1F4DA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DB;</span></dt><dd><input type="text" value="&amp;#x1F4DB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DC;</span></dt><dd><input type="text" value="&amp;#x1F4DC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DD;</span></dt><dd><input type="text" value="&amp;#x1F4DD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DE;</span></dt><dd><input type="text" value="&amp;#x1F4DE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4DF;</span></dt><dd><input type="text" value="&amp;#x1F4DF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E0;</span></dt><dd><input type="text" value="&amp;#x1F4E0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E1;</span></dt><dd><input type="text" value="&amp;#x1F4E1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E2;</span></dt><dd><input type="text" value="&amp;#x1F4E2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E3;</span></dt><dd><input type="text" value="&amp;#x1F4E3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E4;</span></dt><dd><input type="text" value="&amp;#x1F4E4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E5;</span></dt><dd><input type="text" value="&amp;#x1F4E5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E6;</span></dt><dd><input type="text" value="&amp;#x1F4E6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E7;</span></dt><dd><input type="text" value="&amp;#x1F4E7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E8;</span></dt><dd><input type="text" value="&amp;#x1F4E8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4E9;</span></dt><dd><input type="text" value="&amp;#x1F4E9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4EA;</span></dt><dd><input type="text" value="&amp;#x1F4EA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4EB;</span></dt><dd><input type="text" value="&amp;#x1F4EB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4EC;</span></dt><dd><input type="text" value="&amp;#x1F4EC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4ED;</span></dt><dd><input type="text" value="&amp;#x1F4ED;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4EE;</span></dt><dd><input type="text" value="&amp;#x1F4EE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4EF;</span></dt><dd><input type="text" value="&amp;#x1F4EF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F0;</span></dt><dd><input type="text" value="&amp;#x1F4F0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F1;</span></dt><dd><input type="text" value="&amp;#x1F4F1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F2;</span></dt><dd><input type="text" value="&amp;#x1F4F2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F3;</span></dt><dd><input type="text" value="&amp;#x1F4F3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F4;</span></dt><dd><input type="text" value="&amp;#x1F4F4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F5;</span></dt><dd><input type="text" value="&amp;#x1F4F5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F6;</span></dt><dd><input type="text" value="&amp;#x1F4F6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F7;</span></dt><dd><input type="text" value="&amp;#x1F4F7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4F9;</span></dt><dd><input type="text" value="&amp;#x1F4F9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4FA;</span></dt><dd><input type="text" value="&amp;#x1F4FA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4FB;</span></dt><dd><input type="text" value="&amp;#x1F4FB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F4FC;</span></dt><dd><input type="text" value="&amp;#x1F4FC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F500;</span></dt><dd><input type="text" value="&amp;#x1F500;" /><dd></dl>
<dl><dt><span class="emj">&#x1F501;</span></dt><dd><input type="text" value="&amp;#x1F501;" /><dd></dl>
<dl><dt><span class="emj">&#x1F502;</span></dt><dd><input type="text" value="&amp;#x1F502;" /><dd></dl>
<dl><dt><span class="emj">&#x1F503;</span></dt><dd><input type="text" value="&amp;#x1F503;" /><dd></dl>
<dl><dt><span class="emj">&#x1F504;</span></dt><dd><input type="text" value="&amp;#x1F504;" /><dd></dl>
<dl><dt><span class="emj">&#x1F505;</span></dt><dd><input type="text" value="&amp;#x1F505;" /><dd></dl>
<dl><dt><span class="emj">&#x1F506;</span></dt><dd><input type="text" value="&amp;#x1F506;" /><dd></dl>
<dl><dt><span class="emj">&#x1F507;</span></dt><dd><input type="text" value="&amp;#x1F507;" /><dd></dl>
<dl><dt><span class="emj">&#x1F508;</span></dt><dd><input type="text" value="&amp;#x1F508;" /><dd></dl>
<dl><dt><span class="emj">&#x1F509;</span></dt><dd><input type="text" value="&amp;#x1F509;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50A;</span></dt><dd><input type="text" value="&amp;#x1F50A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50B;</span></dt><dd><input type="text" value="&amp;#x1F50B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50C;</span></dt><dd><input type="text" value="&amp;#x1F50C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50D;</span></dt><dd><input type="text" value="&amp;#x1F50D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50E;</span></dt><dd><input type="text" value="&amp;#x1F50E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F50F;</span></dt><dd><input type="text" value="&amp;#x1F50F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F510;</span></dt><dd><input type="text" value="&amp;#x1F510;" /><dd></dl>
<dl><dt><span class="emj">&#x1F511;</span></dt><dd><input type="text" value="&amp;#x1F511;" /><dd></dl>
<dl><dt><span class="emj">&#x1F512;</span></dt><dd><input type="text" value="&amp;#x1F512;" /><dd></dl>
<dl><dt><span class="emj">&#x1F513;</span></dt><dd><input type="text" value="&amp;#x1F513;" /><dd></dl>
<dl><dt><span class="emj">&#x1F514;</span></dt><dd><input type="text" value="&amp;#x1F514;" /><dd></dl>
<dl><dt><span class="emj">&#x1F515;</span></dt><dd><input type="text" value="&amp;#x1F515;" /><dd></dl>
<dl><dt><span class="emj">&#x1F516;</span></dt><dd><input type="text" value="&amp;#x1F516;" /><dd></dl>
<dl><dt><span class="emj">&#x1F517;</span></dt><dd><input type="text" value="&amp;#x1F517;" /><dd></dl>
<dl><dt><span class="emj">&#x1F518;</span></dt><dd><input type="text" value="&amp;#x1F518;" /><dd></dl>
<dl><dt><span class="emj">&#x1F519;</span></dt><dd><input type="text" value="&amp;#x1F519;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51A;</span></dt><dd><input type="text" value="&amp;#x1F51A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51B;</span></dt><dd><input type="text" value="&amp;#x1F51B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51C;</span></dt><dd><input type="text" value="&amp;#x1F51C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51D;</span></dt><dd><input type="text" value="&amp;#x1F51D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51E;</span></dt><dd><input type="text" value="&amp;#x1F51E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F51F;</span></dt><dd><input type="text" value="&amp;#x1F51F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F522;</span></dt><dd><input type="text" value="&amp;#x1F522;" /><dd></dl>
<dl><dt><span class="emj">&#x1F523;</span></dt><dd><input type="text" value="&amp;#x1F523;" /><dd></dl>
<dl><dt><span class="emj">&#x1F525;</span></dt><dd><input type="text" value="&amp;#x1F525;" /><dd></dl>
<dl><dt><span class="emj">&#x1F526;</span></dt><dd><input type="text" value="&amp;#x1F526;" /><dd></dl>
<dl><dt><span class="emj">&#x1F527;</span></dt><dd><input type="text" value="&amp;#x1F527;" /><dd></dl>
<dl><dt><span class="emj">&#x1F528;</span></dt><dd><input type="text" value="&amp;#x1F528;" /><dd></dl>
<dl><dt><span class="emj">&#x1F529;</span></dt><dd><input type="text" value="&amp;#x1F529;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52A;</span></dt><dd><input type="text" value="&amp;#x1F52A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52B;</span></dt><dd><input type="text" value="&amp;#x1F52B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52C;</span></dt><dd><input type="text" value="&amp;#x1F52C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52D;</span></dt><dd><input type="text" value="&amp;#x1F52D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52E;</span></dt><dd><input type="text" value="&amp;#x1F52E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F52F;</span></dt><dd><input type="text" value="&amp;#x1F52F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F530;</span></dt><dd><input type="text" value="&amp;#x1F530;" /><dd></dl>
<dl><dt><span class="emj">&#x1F531;</span></dt><dd><input type="text" value="&amp;#x1F531;" /><dd></dl>
<dl><dt><span class="emj">&#x1F532;</span></dt><dd><input type="text" value="&amp;#x1F532;" /><dd></dl>
<dl><dt><span class="emj">&#x1F533;</span></dt><dd><input type="text" value="&amp;#x1F533;" /><dd></dl>
<dl><dt><span class="emj">&#x1F534;</span></dt><dd><input type="text" value="&amp;#x1F534;" /><dd></dl>
<dl><dt><span class="emj">&#x1F535;</span></dt><dd><input type="text" value="&amp;#x1F535;" /><dd></dl>
<dl><dt><span class="emj">&#x1F536;</span></dt><dd><input type="text" value="&amp;#x1F536;" /><dd></dl>
<dl><dt><span class="emj">&#x1F537;</span></dt><dd><input type="text" value="&amp;#x1F537;" /><dd></dl>
<dl><dt><span class="emj">&#x1F538;</span></dt><dd><input type="text" value="&amp;#x1F538;" /><dd></dl>
<dl><dt><span class="emj">&#x1F539;</span></dt><dd><input type="text" value="&amp;#x1F539;" /><dd></dl>
<dl><dt><span class="emj">&#x1F53A;</span></dt><dd><input type="text" value="&amp;#x1F53A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F53B;</span></dt><dd><input type="text" value="&amp;#x1F53B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F53C;</span></dt><dd><input type="text" value="&amp;#x1F53C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F53D;</span></dt><dd><input type="text" value="&amp;#x1F53D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F550;</span></dt><dd><input type="text" value="&amp;#x1F550;" /><dd></dl>
<dl><dt><span class="emj">&#x1F551;</span></dt><dd><input type="text" value="&amp;#x1F551;" /><dd></dl>
<dl><dt><span class="emj">&#x1F552;</span></dt><dd><input type="text" value="&amp;#x1F552;" /><dd></dl>
<dl><dt><span class="emj">&#x1F553;</span></dt><dd><input type="text" value="&amp;#x1F553;" /><dd></dl>
<dl><dt><span class="emj">&#x1F554;</span></dt><dd><input type="text" value="&amp;#x1F554;" /><dd></dl>
<dl><dt><span class="emj">&#x1F555;</span></dt><dd><input type="text" value="&amp;#x1F555;" /><dd></dl>
<dl><dt><span class="emj">&#x1F556;</span></dt><dd><input type="text" value="&amp;#x1F556;" /><dd></dl>
<dl><dt><span class="emj">&#x1F557;</span></dt><dd><input type="text" value="&amp;#x1F557;" /><dd></dl>
<dl><dt><span class="emj">&#x1F558;</span></dt><dd><input type="text" value="&amp;#x1F558;" /><dd></dl>
<dl><dt><span class="emj">&#x1F559;</span></dt><dd><input type="text" value="&amp;#x1F559;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55A;</span></dt><dd><input type="text" value="&amp;#x1F55A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55B;</span></dt><dd><input type="text" value="&amp;#x1F55B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55C;</span></dt><dd><input type="text" value="&amp;#x1F55C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55D;</span></dt><dd><input type="text" value="&amp;#x1F55D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55E;</span></dt><dd><input type="text" value="&amp;#x1F55E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F55F;</span></dt><dd><input type="text" value="&amp;#x1F55F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F560;</span></dt><dd><input type="text" value="&amp;#x1F560;" /><dd></dl>
<dl><dt><span class="emj">&#x1F561;</span></dt><dd><input type="text" value="&amp;#x1F561;" /><dd></dl>
<dl><dt><span class="emj">&#x1F562;</span></dt><dd><input type="text" value="&amp;#x1F562;" /><dd></dl>
<dl><dt><span class="emj">&#x1F563;</span></dt><dd><input type="text" value="&amp;#x1F563;" /><dd></dl>
<dl><dt><span class="emj">&#x1F564;</span></dt><dd><input type="text" value="&amp;#x1F564;" /><dd></dl>
<dl><dt><span class="emj">&#x1F565;</span></dt><dd><input type="text" value="&amp;#x1F565;" /><dd></dl>
<dl><dt><span class="emj">&#x1F566;</span></dt><dd><input type="text" value="&amp;#x1F566;" /><dd></dl>
<dl><dt><span class="emj">&#x1F567;</span></dt><dd><input type="text" value="&amp;#x1F567;" /><dd></dl>
<dl><dt><span class="emj">&#x1F5FB;</span></dt><dd><input type="text" value="&amp;#x1F5FB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F5FC;</span></dt><dd><input type="text" value="&amp;#x1F5FC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F5FD;</span></dt><dd><input type="text" value="&amp;#x1F5FD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F5FE;</span></dt><dd><input type="text" value="&amp;#x1F5FE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F5FF;</span></dt><dd><input type="text" value="&amp;#x1F5FF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F600;</span></dt><dd><input type="text" value="&amp;#x1F600;" /><dd></dl>
<dl><dt><span class="emj">&#x1F601;</span></dt><dd><input type="text" value="&amp;#x1F601;" /><dd></dl>
<dl><dt><span class="emj">&#x1F602;</span></dt><dd><input type="text" value="&amp;#x1F602;" /><dd></dl>
<dl><dt><span class="emj">&#x1F603;</span></dt><dd><input type="text" value="&amp;#x1F603;" /><dd></dl>
<dl><dt><span class="emj">&#x1F604;</span></dt><dd><input type="text" value="&amp;#x1F604;" /><dd></dl>
<dl><dt><span class="emj">&#x1F605;</span></dt><dd><input type="text" value="&amp;#x1F605;" /><dd></dl>
<dl><dt><span class="emj">&#x1F606;</span></dt><dd><input type="text" value="&amp;#x1F606;" /><dd></dl>
<dl><dt><span class="emj">&#x1F607;</span></dt><dd><input type="text" value="&amp;#x1F607;" /><dd></dl>
<dl><dt><span class="emj">&#x1F608;</span></dt><dd><input type="text" value="&amp;#x1F608;" /><dd></dl>
<dl><dt><span class="emj">&#x1F609;</span></dt><dd><input type="text" value="&amp;#x1F609;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60A;</span></dt><dd><input type="text" value="&amp;#x1F60A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60B;</span></dt><dd><input type="text" value="&amp;#x1F60B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60C;</span></dt><dd><input type="text" value="&amp;#x1F60C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60D;</span></dt><dd><input type="text" value="&amp;#x1F60D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60E;</span></dt><dd><input type="text" value="&amp;#x1F60E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F60F;</span></dt><dd><input type="text" value="&amp;#x1F60F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F610;</span></dt><dd><input type="text" value="&amp;#x1F610;" /><dd></dl>
<dl><dt><span class="emj">&#x1F611;</span></dt><dd><input type="text" value="&amp;#x1F611;" /><dd></dl>
<dl><dt><span class="emj">&#x1F612;</span></dt><dd><input type="text" value="&amp;#x1F612;" /><dd></dl>
<dl><dt><span class="emj">&#x1F613;</span></dt><dd><input type="text" value="&amp;#x1F613;" /><dd></dl>
<dl><dt><span class="emj">&#x1F614;</span></dt><dd><input type="text" value="&amp;#x1F614;" /><dd></dl>
<dl><dt><span class="emj">&#x1F615;</span></dt><dd><input type="text" value="&amp;#x1F615;" /><dd></dl>
<dl><dt><span class="emj">&#x1F616;</span></dt><dd><input type="text" value="&amp;#x1F616;" /><dd></dl>
<dl><dt><span class="emj">&#x1F617;</span></dt><dd><input type="text" value="&amp;#x1F617;" /><dd></dl>
<dl><dt><span class="emj">&#x1F618;</span></dt><dd><input type="text" value="&amp;#x1F618;" /><dd></dl>
<dl><dt><span class="emj">&#x1F619;</span></dt><dd><input type="text" value="&amp;#x1F619;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61A;</span></dt><dd><input type="text" value="&amp;#x1F61A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61B;</span></dt><dd><input type="text" value="&amp;#x1F61B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61C;</span></dt><dd><input type="text" value="&amp;#x1F61C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61D;</span></dt><dd><input type="text" value="&amp;#x1F61D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61E;</span></dt><dd><input type="text" value="&amp;#x1F61E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F61F;</span></dt><dd><input type="text" value="&amp;#x1F61F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F620;</span></dt><dd><input type="text" value="&amp;#x1F620;" /><dd></dl>
<dl><dt><span class="emj">&#x1F621;</span></dt><dd><input type="text" value="&amp;#x1F621;" /><dd></dl>
<dl><dt><span class="emj">&#x1F622;</span></dt><dd><input type="text" value="&amp;#x1F622;" /><dd></dl>
<dl><dt><span class="emj">&#x1F623;</span></dt><dd><input type="text" value="&amp;#x1F623;" /><dd></dl>
<dl><dt><span class="emj">&#x1F624;</span></dt><dd><input type="text" value="&amp;#x1F624;" /><dd></dl>
<dl><dt><span class="emj">&#x1F625;</span></dt><dd><input type="text" value="&amp;#x1F625;" /><dd></dl>
<dl><dt><span class="emj">&#x1F626;</span></dt><dd><input type="text" value="&amp;#x1F626;" /><dd></dl>
<dl><dt><span class="emj">&#x1F627;</span></dt><dd><input type="text" value="&amp;#x1F627;" /><dd></dl>
<dl><dt><span class="emj">&#x1F628;</span></dt><dd><input type="text" value="&amp;#x1F628;" /><dd></dl>
<dl><dt><span class="emj">&#x1F629;</span></dt><dd><input type="text" value="&amp;#x1F629;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62A;</span></dt><dd><input type="text" value="&amp;#x1F62A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62B;</span></dt><dd><input type="text" value="&amp;#x1F62B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62C;</span></dt><dd><input type="text" value="&amp;#x1F62C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62D;</span></dt><dd><input type="text" value="&amp;#x1F62D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62E;</span></dt><dd><input type="text" value="&amp;#x1F62E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F62F;</span></dt><dd><input type="text" value="&amp;#x1F62F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F630;</span></dt><dd><input type="text" value="&amp;#x1F630;" /><dd></dl>
<dl><dt><span class="emj">&#x1F631;</span></dt><dd><input type="text" value="&amp;#x1F631;" /><dd></dl>
<dl><dt><span class="emj">&#x1F632;</span></dt><dd><input type="text" value="&amp;#x1F632;" /><dd></dl>
<dl><dt><span class="emj">&#x1F633;</span></dt><dd><input type="text" value="&amp;#x1F633;" /><dd></dl>
<dl><dt><span class="emj">&#x1F634;</span></dt><dd><input type="text" value="&amp;#x1F634;" /><dd></dl>
<dl><dt><span class="emj">&#x1F635;</span></dt><dd><input type="text" value="&amp;#x1F635;" /><dd></dl>
<dl><dt><span class="emj">&#x1F636;</span></dt><dd><input type="text" value="&amp;#x1F636;" /><dd></dl>
<dl><dt><span class="emj">&#x1F637;</span></dt><dd><input type="text" value="&amp;#x1F637;" /><dd></dl>
<dl><dt><span class="emj">&#x1F638;</span></dt><dd><input type="text" value="&amp;#x1F638;" /><dd></dl>
<dl><dt><span class="emj">&#x1F639;</span></dt><dd><input type="text" value="&amp;#x1F639;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63A;</span></dt><dd><input type="text" value="&amp;#x1F63A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63B;</span></dt><dd><input type="text" value="&amp;#x1F63B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63C;</span></dt><dd><input type="text" value="&amp;#x1F63C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63D;</span></dt><dd><input type="text" value="&amp;#x1F63D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63E;</span></dt><dd><input type="text" value="&amp;#x1F63E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F63F;</span></dt><dd><input type="text" value="&amp;#x1F63F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F640;</span></dt><dd><input type="text" value="&amp;#x1F640;" /><dd></dl>
<dl><dt><span class="emj">&#x1F645;</span></dt><dd><input type="text" value="&amp;#x1F645;" /><dd></dl>
<dl><dt><span class="emj">&#x1F646;</span></dt><dd><input type="text" value="&amp;#x1F646;" /><dd></dl>
<dl><dt><span class="emj">&#x1F647;</span></dt><dd><input type="text" value="&amp;#x1F647;" /><dd></dl>
<dl><dt><span class="emj">&#x1F648;</span></dt><dd><input type="text" value="&amp;#x1F648;" /><dd></dl>
<dl><dt><span class="emj">&#x1F649;</span></dt><dd><input type="text" value="&amp;#x1F649;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64A;</span></dt><dd><input type="text" value="&amp;#x1F64A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64B;</span></dt><dd><input type="text" value="&amp;#x1F64B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64C;</span></dt><dd><input type="text" value="&amp;#x1F64C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64D;</span></dt><dd><input type="text" value="&amp;#x1F64D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64E;</span></dt><dd><input type="text" value="&amp;#x1F64E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F64F;</span></dt><dd><input type="text" value="&amp;#x1F64F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F680;</span></dt><dd><input type="text" value="&amp;#x1F680;" /><dd></dl>
<dl><dt><span class="emj">&#x1F681;</span></dt><dd><input type="text" value="&amp;#x1F681;" /><dd></dl>
<dl><dt><span class="emj">&#x1F682;</span></dt><dd><input type="text" value="&amp;#x1F682;" /><dd></dl>
<dl><dt><span class="emj">&#x1F683;</span></dt><dd><input type="text" value="&amp;#x1F683;" /><dd></dl>
<dl><dt><span class="emj">&#x1F684;</span></dt><dd><input type="text" value="&amp;#x1F684;" /><dd></dl>
<dl><dt><span class="emj">&#x1F685;</span></dt><dd><input type="text" value="&amp;#x1F685;" /><dd></dl>
<dl><dt><span class="emj">&#x1F686;</span></dt><dd><input type="text" value="&amp;#x1F686;" /><dd></dl>
<dl><dt><span class="emj">&#x1F687;</span></dt><dd><input type="text" value="&amp;#x1F687;" /><dd></dl>
<dl><dt><span class="emj">&#x1F688;</span></dt><dd><input type="text" value="&amp;#x1F688;" /><dd></dl>
<dl><dt><span class="emj">&#x1F689;</span></dt><dd><input type="text" value="&amp;#x1F689;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68A;</span></dt><dd><input type="text" value="&amp;#x1F68A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68B;</span></dt><dd><input type="text" value="&amp;#x1F68B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68C;</span></dt><dd><input type="text" value="&amp;#x1F68C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68D;</span></dt><dd><input type="text" value="&amp;#x1F68D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68E;</span></dt><dd><input type="text" value="&amp;#x1F68E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F68F;</span></dt><dd><input type="text" value="&amp;#x1F68F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F690;</span></dt><dd><input type="text" value="&amp;#x1F690;" /><dd></dl>
<dl><dt><span class="emj">&#x1F691;</span></dt><dd><input type="text" value="&amp;#x1F691;" /><dd></dl>
<dl><dt><span class="emj">&#x1F692;</span></dt><dd><input type="text" value="&amp;#x1F692;" /><dd></dl>
<dl><dt><span class="emj">&#x1F693;</span></dt><dd><input type="text" value="&amp;#x1F693;" /><dd></dl>
<dl><dt><span class="emj">&#x1F694;</span></dt><dd><input type="text" value="&amp;#x1F694;" /><dd></dl>
<dl><dt><span class="emj">&#x1F695;</span></dt><dd><input type="text" value="&amp;#x1F695;" /><dd></dl>
<dl><dt><span class="emj">&#x1F696;</span></dt><dd><input type="text" value="&amp;#x1F696;" /><dd></dl>
<dl><dt><span class="emj">&#x1F697;</span></dt><dd><input type="text" value="&amp;#x1F697;" /><dd></dl>
<dl><dt><span class="emj">&#x1F698;</span></dt><dd><input type="text" value="&amp;#x1F698;" /><dd></dl>
<dl><dt><span class="emj">&#x1F699;</span></dt><dd><input type="text" value="&amp;#x1F699;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69A;</span></dt><dd><input type="text" value="&amp;#x1F69A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69B;</span></dt><dd><input type="text" value="&amp;#x1F69B;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69C;</span></dt><dd><input type="text" value="&amp;#x1F69C;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69D;</span></dt><dd><input type="text" value="&amp;#x1F69D;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69E;</span></dt><dd><input type="text" value="&amp;#x1F69E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F69F;</span></dt><dd><input type="text" value="&amp;#x1F69F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A0;</span></dt><dd><input type="text" value="&amp;#x1F6A0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A1;</span></dt><dd><input type="text" value="&amp;#x1F6A1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A2;</span></dt><dd><input type="text" value="&amp;#x1F6A2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A3;</span></dt><dd><input type="text" value="&amp;#x1F6A3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A4;</span></dt><dd><input type="text" value="&amp;#x1F6A4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A5;</span></dt><dd><input type="text" value="&amp;#x1F6A5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A6;</span></dt><dd><input type="text" value="&amp;#x1F6A6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A7;</span></dt><dd><input type="text" value="&amp;#x1F6A7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A8;</span></dt><dd><input type="text" value="&amp;#x1F6A8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6A9;</span></dt><dd><input type="text" value="&amp;#x1F6A9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AA;</span></dt><dd><input type="text" value="&amp;#x1F6AA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AB;</span></dt><dd><input type="text" value="&amp;#x1F6AB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AC;</span></dt><dd><input type="text" value="&amp;#x1F6AC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AD;</span></dt><dd><input type="text" value="&amp;#x1F6AD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AE;</span></dt><dd><input type="text" value="&amp;#x1F6AE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6AF;</span></dt><dd><input type="text" value="&amp;#x1F6AF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B0;</span></dt><dd><input type="text" value="&amp;#x1F6B0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B1;</span></dt><dd><input type="text" value="&amp;#x1F6B1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B2;</span></dt><dd><input type="text" value="&amp;#x1F6B2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B3;</span></dt><dd><input type="text" value="&amp;#x1F6B3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B4;</span></dt><dd><input type="text" value="&amp;#x1F6B4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B5;</span></dt><dd><input type="text" value="&amp;#x1F6B5;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B6;</span></dt><dd><input type="text" value="&amp;#x1F6B6;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B7;</span></dt><dd><input type="text" value="&amp;#x1F6B7;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B8;</span></dt><dd><input type="text" value="&amp;#x1F6B8;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6B9;</span></dt><dd><input type="text" value="&amp;#x1F6B9;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BA;</span></dt><dd><input type="text" value="&amp;#x1F6BA;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BB;</span></dt><dd><input type="text" value="&amp;#x1F6BB;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BC;</span></dt><dd><input type="text" value="&amp;#x1F6BC;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BD;</span></dt><dd><input type="text" value="&amp;#x1F6BD;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BE;</span></dt><dd><input type="text" value="&amp;#x1F6BE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6BF;</span></dt><dd><input type="text" value="&amp;#x1F6BF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C0;</span></dt><dd><input type="text" value="&amp;#x1F6C0;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C1;</span></dt><dd><input type="text" value="&amp;#x1F6C1;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C2;</span></dt><dd><input type="text" value="&amp;#x1F6C2;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C3;</span></dt><dd><input type="text" value="&amp;#x1F6C3;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C4;</span></dt><dd><input type="text" value="&amp;#x1F6C4;" /><dd></dl>
<dl><dt><span class="emj">&#x1F6C5;</span></dt><dd><input type="text" value="&amp;#x1F6C5;" /><dd></dl>
<dl><dt><span class="emj">&#x00A9;</span></dt><dd><input type="text" value="&amp;#x00A9;" /><dd></dl>
<dl><dt><span class="emj">&#x00AE;</span></dt><dd><input type="text" value="&amp;#x00AE;" /><dd></dl>
<dl><dt><span class="emj">&#x1F004;</span></dt><dd><input type="text" value="&amp;#x1F004;" /><dd></dl>
<dl><dt><span class="emj">&#x1F0CF;</span></dt><dd><input type="text" value="&amp;#x1F0CF;" /><dd></dl>
<dl><dt><span class="emj">&#x1F170;</span></dt><dd><input type="text" value="&amp;#x1F170;" /><dd></dl>
<dl><dt><span class="emj">&#x1F171;</span></dt><dd><input type="text" value="&amp;#x1F171;" /><dd></dl>
<dl><dt><span class="emj">&#x1F17E;</span></dt><dd><input type="text" value="&amp;#x1F17E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F17F;</span></dt><dd><input type="text" value="&amp;#x1F17F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F18E;</span></dt><dd><input type="text" value="&amp;#x1F18E;" /><dd></dl>
<dl><dt><span class="emj">&#x1F191;</span></dt><dd><input type="text" value="&amp;#x1F191;" /><dd></dl>
<dl><dt><span class="emj">&#x1F192;</span></dt><dd><input type="text" value="&amp;#x1F192;" /><dd></dl>
<dl><dt><span class="emj">&#x1F193;</span></dt><dd><input type="text" value="&amp;#x1F193;" /><dd></dl>
<dl><dt><span class="emj">&#x1F194;</span></dt><dd><input type="text" value="&amp;#x1F194;" /><dd></dl>
<dl><dt><span class="emj">&#x1F195;</span></dt><dd><input type="text" value="&amp;#x1F195;" /><dd></dl>
<dl><dt><span class="emj">&#x1F196;</span></dt><dd><input type="text" value="&amp;#x1F196;" /><dd></dl>
<dl><dt><span class="emj">&#x1F197;</span></dt><dd><input type="text" value="&amp;#x1F197;" /><dd></dl>
<dl><dt><span class="emj">&#x1F198;</span></dt><dd><input type="text" value="&amp;#x1F198;" /><dd></dl>
<dl><dt><span class="emj">&#x1F199;</span></dt><dd><input type="text" value="&amp;#x1F199;" /><dd></dl>
<dl><dt><span class="emj">&#x1F19A;</span></dt><dd><input type="text" value="&amp;#x1F19A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F201;</span></dt><dd><input type="text" value="&amp;#x1F201;" /><dd></dl>
<dl><dt><span class="emj">&#x1F202;</span></dt><dd><input type="text" value="&amp;#x1F202;" /><dd></dl>
<dl><dt><span class="emj">&#x1F21A;</span></dt><dd><input type="text" value="&amp;#x1F21A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F22F;</span></dt><dd><input type="text" value="&amp;#x1F22F;" /><dd></dl>
<dl><dt><span class="emj">&#x1F232;</span></dt><dd><input type="text" value="&amp;#x1F232;" /><dd></dl>
<dl><dt><span class="emj">&#x1F233;</span></dt><dd><input type="text" value="&amp;#x1F233;" /><dd></dl>
<dl><dt><span class="emj">&#x1F234;</span></dt><dd><input type="text" value="&amp;#x1F234;" /><dd></dl>
<dl><dt><span class="emj">&#x1F235;</span></dt><dd><input type="text" value="&amp;#x1F235;" /><dd></dl>
<dl><dt><span class="emj">&#x1F236;</span></dt><dd><input type="text" value="&amp;#x1F236;" /><dd></dl>
<dl><dt><span class="emj">&#x1F237;</span></dt><dd><input type="text" value="&amp;#x1F237;" /><dd></dl>
<dl><dt><span class="emj">&#x1F238;</span></dt><dd><input type="text" value="&amp;#x1F238;" /><dd></dl>
<dl><dt><span class="emj">&#x1F239;</span></dt><dd><input type="text" value="&amp;#x1F239;" /><dd></dl>
<dl><dt><span class="emj">&#x1F23A;</span></dt><dd><input type="text" value="&amp;#x1F23A;" /><dd></dl>
<dl><dt><span class="emj">&#x1F250;</span></dt><dd><input type="text" value="&amp;#x1F250;" /><dd></dl>
<dl><dt><span class="emj">&#x1F251;</span></dt><dd><input type="text" value="&amp;#x1F251;" /><dd></dl>
<dl><dt><span class="emj">&#x203C;</span></dt><dd><input type="text" value="&amp;#x203C;" /><dd></dl>
<dl><dt><span class="emj">&#x2049;</span></dt><dd><input type="text" value="&amp;#x2049;" /><dd></dl>
<dl><dt><span class="emj">&#x20E3;</span></dt><dd><input type="text" value="&amp;#x20E3;" /><dd></dl>
<dl><dt><span class="emj">&#x2122;</span></dt><dd><input type="text" value="&amp;#x2122;" /><dd></dl>
<dl><dt><span class="emj">&#x2139;</span></dt><dd><input type="text" value="&amp;#x2139;" /><dd></dl>
<dl><dt><span class="emj">&#x2194;</span></dt><dd><input type="text" value="&amp;#x2194;" /><dd></dl>
<dl><dt><span class="emj">&#x2195;</span></dt><dd><input type="text" value="&amp;#x2195;" /><dd></dl>
<dl><dt><span class="emj">&#x2196;</span></dt><dd><input type="text" value="&amp;#x2196;" /><dd></dl>
<dl><dt><span class="emj">&#x2197;</span></dt><dd><input type="text" value="&amp;#x2197;" /><dd></dl>
<dl><dt><span class="emj">&#x2198;</span></dt><dd><input type="text" value="&amp;#x2198;" /><dd></dl>
<dl><dt><span class="emj">&#x2199;</span></dt><dd><input type="text" value="&amp;#x2199;" /><dd></dl>
<dl><dt><span class="emj">&#x21A9;</span></dt><dd><input type="text" value="&amp;#x21A9;" /><dd></dl>
<dl><dt><span class="emj">&#x21AA;</span></dt><dd><input type="text" value="&amp;#x21AA;" /><dd></dl>
<dl><dt><span class="emj">&#x231A;</span></dt><dd><input type="text" value="&amp;#x231A;" /><dd></dl>
<dl><dt><span class="emj">&#x231B;</span></dt><dd><input type="text" value="&amp;#x231B;" /><dd></dl>
<dl><dt><span class="emj">&#x23E9;</span></dt><dd><input type="text" value="&amp;#x23E9;" /><dd></dl>
<dl><dt><span class="emj">&#x23EA;</span></dt><dd><input type="text" value="&amp;#x23EA;" /><dd></dl>
<dl><dt><span class="emj">&#x23EB;</span></dt><dd><input type="text" value="&amp;#x23EB;" /><dd></dl>
<dl><dt><span class="emj">&#x23EC;</span></dt><dd><input type="text" value="&amp;#x23EC;" /><dd></dl>
<dl><dt><span class="emj">&#x23F0;</span></dt><dd><input type="text" value="&amp;#x23F0;" /><dd></dl>
<dl><dt><span class="emj">&#x23F3;</span></dt><dd><input type="text" value="&amp;#x23F3;" /><dd></dl>
<dl><dt><span class="emj">&#x24C2;</span></dt><dd><input type="text" value="&amp;#x24C2;" /><dd></dl>
<dl><dt><span class="emj">&#x25AA;</span></dt><dd><input type="text" value="&amp;#x25AA;" /><dd></dl>
<dl><dt><span class="emj">&#x25AB;</span></dt><dd><input type="text" value="&amp;#x25AB;" /><dd></dl>
<dl><dt><span class="emj">&#x25B6;</span></dt><dd><input type="text" value="&amp;#x25B6;" /><dd></dl>
<dl><dt><span class="emj">&#x25C0;</span></dt><dd><input type="text" value="&amp;#x25C0;" /><dd></dl>
<dl><dt><span class="emj">&#x25FB;</span></dt><dd><input type="text" value="&amp;#x25FB;" /><dd></dl>
<dl><dt><span class="emj">&#x25FC;</span></dt><dd><input type="text" value="&amp;#x25FC;" /><dd></dl>
<dl><dt><span class="emj">&#x25FD;</span></dt><dd><input type="text" value="&amp;#x25FD;" /><dd></dl>
<dl><dt><span class="emj">&#x25FE;</span></dt><dd><input type="text" value="&amp;#x25FE;" /><dd></dl>
<dl><dt><span class="emj">&#x2600;</span></dt><dd><input type="text" value="&amp;#x2600;" /><dd></dl>
<dl><dt><span class="emj">&#x2601;</span></dt><dd><input type="text" value="&amp;#x2601;" /><dd></dl>
<dl><dt><span class="emj">&#x260E;</span></dt><dd><input type="text" value="&amp;#x260E;" /><dd></dl>
<dl><dt><span class="emj">&#x2611;</span></dt><dd><input type="text" value="&amp;#x2611;" /><dd></dl>
<dl><dt><span class="emj">&#x2614;</span></dt><dd><input type="text" value="&amp;#x2614;" /><dd></dl>
<dl><dt><span class="emj">&#x2615;</span></dt><dd><input type="text" value="&amp;#x2615;" /><dd></dl>
<dl><dt><span class="emj">&#x261D;</span></dt><dd><input type="text" value="&amp;#x261D;" /><dd></dl>
<dl><dt><span class="emj">&#x263A;</span></dt><dd><input type="text" value="&amp;#x263A;" /><dd></dl>
<dl><dt><span class="emj">&#x2648;</span></dt><dd><input type="text" value="&amp;#x2648;" /><dd></dl>
<dl><dt><span class="emj">&#x2649;</span></dt><dd><input type="text" value="&amp;#x2649;" /><dd></dl>
<dl><dt><span class="emj">&#x264A;</span></dt><dd><input type="text" value="&amp;#x264A;" /><dd></dl>
<dl><dt><span class="emj">&#x264B;</span></dt><dd><input type="text" value="&amp;#x264B;" /><dd></dl>
<dl><dt><span class="emj">&#x264C;</span></dt><dd><input type="text" value="&amp;#x264C;" /><dd></dl>
<dl><dt><span class="emj">&#x264D;</span></dt><dd><input type="text" value="&amp;#x264D;" /><dd></dl>
<dl><dt><span class="emj">&#x264E;</span></dt><dd><input type="text" value="&amp;#x264E;" /><dd></dl>
<dl><dt><span class="emj">&#x264F;</span></dt><dd><input type="text" value="&amp;#x264F;" /><dd></dl>
<dl><dt><span class="emj">&#x2650;</span></dt><dd><input type="text" value="&amp;#x2650;" /><dd></dl>
<dl><dt><span class="emj">&#x2651;</span></dt><dd><input type="text" value="&amp;#x2651;" /><dd></dl>
<dl><dt><span class="emj">&#x2652;</span></dt><dd><input type="text" value="&amp;#x2652;" /><dd></dl>
<dl><dt><span class="emj">&#x2653;</span></dt><dd><input type="text" value="&amp;#x2653;" /><dd></dl>
<dl><dt><span class="emj">&#x2660;</span></dt><dd><input type="text" value="&amp;#x2660;" /><dd></dl>
<dl><dt><span class="emj">&#x2663;</span></dt><dd><input type="text" value="&amp;#x2663;" /><dd></dl>
<dl><dt><span class="emj">&#x2665;</span></dt><dd><input type="text" value="&amp;#x2665;" /><dd></dl>
<dl><dt><span class="emj">&#x2666;</span></dt><dd><input type="text" value="&amp;#x2666;" /><dd></dl>
<dl><dt><span class="emj">&#x2668;</span></dt><dd><input type="text" value="&amp;#x2668;" /><dd></dl>
<dl><dt><span class="emj">&#x267B;</span></dt><dd><input type="text" value="&amp;#x267B;" /><dd></dl>
<dl><dt><span class="emj">&#x267F;</span></dt><dd><input type="text" value="&amp;#x267F;" /><dd></dl>
<dl><dt><span class="emj">&#x2693;</span></dt><dd><input type="text" value="&amp;#x2693;" /><dd></dl>
<dl><dt><span class="emj">&#x26A0;</span></dt><dd><input type="text" value="&amp;#x26A0;" /><dd></dl>
<dl><dt><span class="emj">&#x26A1;</span></dt><dd><input type="text" value="&amp;#x26A1;" /><dd></dl>
<dl><dt><span class="emj">&#x26AA;</span></dt><dd><input type="text" value="&amp;#x26AA;" /><dd></dl>
<dl><dt><span class="emj">&#x26AB;</span></dt><dd><input type="text" value="&amp;#x26AB;" /><dd></dl>
<dl><dt><span class="emj">&#x26BD;</span></dt><dd><input type="text" value="&amp;#x26BD;" /><dd></dl>
<dl><dt><span class="emj">&#x26BE;</span></dt><dd><input type="text" value="&amp;#x26BE;" /><dd></dl>
<dl><dt><span class="emj">&#x26C4;</span></dt><dd><input type="text" value="&amp;#x26C4;" /><dd></dl>
<dl><dt><span class="emj">&#x26C5;</span></dt><dd><input type="text" value="&amp;#x26C5;" /><dd></dl>
<dl><dt><span class="emj">&#x26CE;</span></dt><dd><input type="text" value="&amp;#x26CE;" /><dd></dl>
<dl><dt><span class="emj">&#x26D4;</span></dt><dd><input type="text" value="&amp;#x26D4;" /><dd></dl>
<dl><dt><span class="emj">&#x26EA;</span></dt><dd><input type="text" value="&amp;#x26EA;" /><dd></dl>
<dl><dt><span class="emj">&#x26F2;</span></dt><dd><input type="text" value="&amp;#x26F2;" /><dd></dl>
<dl><dt><span class="emj">&#x26F3;</span></dt><dd><input type="text" value="&amp;#x26F3;" /><dd></dl>
<dl><dt><span class="emj">&#x26F5;</span></dt><dd><input type="text" value="&amp;#x26F5;" /><dd></dl>
<dl><dt><span class="emj">&#x26FA;</span></dt><dd><input type="text" value="&amp;#x26FA;" /><dd></dl>
<dl><dt><span class="emj">&#x26FD;</span></dt><dd><input type="text" value="&amp;#x26FD;" /><dd></dl>
<dl><dt><span class="emj">&#x2702;</span></dt><dd><input type="text" value="&amp;#x2702;" /><dd></dl>
<dl><dt><span class="emj">&#x2705;</span></dt><dd><input type="text" value="&amp;#x2705;" /><dd></dl>
<dl><dt><span class="emj">&#x2708;</span></dt><dd><input type="text" value="&amp;#x2708;" /><dd></dl>
<dl><dt><span class="emj">&#x2709;</span></dt><dd><input type="text" value="&amp;#x2709;" /><dd></dl>
<dl><dt><span class="emj">&#x270A;</span></dt><dd><input type="text" value="&amp;#x270A;" /><dd></dl>
<dl><dt><span class="emj">&#x270B;</span></dt><dd><input type="text" value="&amp;#x270B;" /><dd></dl>
<dl><dt><span class="emj">&#x270C;</span></dt><dd><input type="text" value="&amp;#x270C;" /><dd></dl>
<dl><dt><span class="emj">&#x270F;</span></dt><dd><input type="text" value="&amp;#x270F;" /><dd></dl>
<dl><dt><span class="emj">&#x2712;</span></dt><dd><input type="text" value="&amp;#x2712;" /><dd></dl>
<dl><dt><span class="emj">&#x2714;</span></dt><dd><input type="text" value="&amp;#x2714;" /><dd></dl>
<dl><dt><span class="emj">&#x2716;</span></dt><dd><input type="text" value="&amp;#x2716;" /><dd></dl>
<dl><dt><span class="emj">&#x2728;</span></dt><dd><input type="text" value="&amp;#x2728;" /><dd></dl>
<dl><dt><span class="emj">&#x2733;</span></dt><dd><input type="text" value="&amp;#x2733;" /><dd></dl>
<dl><dt><span class="emj">&#x2734;</span></dt><dd><input type="text" value="&amp;#x2734;" /><dd></dl>
<dl><dt><span class="emj">&#x2744;</span></dt><dd><input type="text" value="&amp;#x2744;" /><dd></dl>
<dl><dt><span class="emj">&#x2747;</span></dt><dd><input type="text" value="&amp;#x2747;" /><dd></dl>
<dl><dt><span class="emj">&#x274C;</span></dt><dd><input type="text" value="&amp;#x274C;" /><dd></dl>
<dl><dt><span class="emj">&#x274E;</span></dt><dd><input type="text" value="&amp;#x274E;" /><dd></dl>
<dl><dt><span class="emj">&#x2753;</span></dt><dd><input type="text" value="&amp;#x2753;" /><dd></dl>
<dl><dt><span class="emj">&#x2754;</span></dt><dd><input type="text" value="&amp;#x2754;" /><dd></dl>
<dl><dt><span class="emj">&#x2755;</span></dt><dd><input type="text" value="&amp;#x2755;" /><dd></dl>
<dl><dt><span class="emj">&#x2757;</span></dt><dd><input type="text" value="&amp;#x2757;" /><dd></dl>
<dl><dt><span class="emj">&#x2764;</span></dt><dd><input type="text" value="&amp;#x2764;" /><dd></dl>
<dl><dt><span class="emj">&#x2795;</span></dt><dd><input type="text" value="&amp;#x2795;" /><dd></dl>
<dl><dt><span class="emj">&#x2796;</span></dt><dd><input type="text" value="&amp;#x2796;" /><dd></dl>
<dl><dt><span class="emj">&#x2797;</span></dt><dd><input type="text" value="&amp;#x2797;" /><dd></dl>
<dl><dt><span class="emj">&#x27A1;</span></dt><dd><input type="text" value="&amp;#x27A1;" /><dd></dl>
<dl><dt><span class="emj">&#x27B0;</span></dt><dd><input type="text" value="&amp;#x27B0;" /><dd></dl>
<dl><dt><span class="emj">&#x27BF;</span></dt><dd><input type="text" value="&amp;#x27BF;" /><dd></dl>
<dl><dt><span class="emj">&#x2934;</span></dt><dd><input type="text" value="&amp;#x2934;" /><dd></dl>
<dl><dt><span class="emj">&#x2935;</span></dt><dd><input type="text" value="&amp;#x2935;" /><dd></dl>
<dl><dt><span class="emj">&#x2B05;</span></dt><dd><input type="text" value="&amp;#x2B05;" /><dd></dl>
<dl><dt><span class="emj">&#x2B06;</span></dt><dd><input type="text" value="&amp;#x2B06;" /><dd></dl>
<dl><dt><span class="emj">&#x2B07;</span></dt><dd><input type="text" value="&amp;#x2B07;" /><dd></dl>
<dl><dt><span class="emj">&#x2B1B;</span></dt><dd><input type="text" value="&amp;#x2B1B;" /><dd></dl>
<dl><dt><span class="emj">&#x2B1C;</span></dt><dd><input type="text" value="&amp;#x2B1C;" /><dd></dl>
<dl><dt><span class="emj">&#x2B50;</span></dt><dd><input type="text" value="&amp;#x2B50;" /><dd></dl>
<dl><dt><span class="emj">&#x2B55;</span></dt><dd><input type="text" value="&amp;#x2B55;" /><dd></dl>
<dl><dt><span class="emj">&#x3030;</span></dt><dd><input type="text" value="&amp;#x3030;" /><dd></dl>
<dl><dt><span class="emj">&#x303D;</span></dt><dd><input type="text" value="&amp;#x303D;" /><dd></dl>
<dl><dt><span class="emj">&#x3297;</span></dt><dd><input type="text" value="&amp;#x3297;" /><dd></dl>
<dl><dt><span class="emj">&#x3299;</span></dt><dd><input type="text" value="&amp;#x3299;" /><dd></dl>
<dl><dt><span class="emj">&#xE50A;</span></dt><dd><input type="text" value="&amp;#xE50A;" /><dd></dl>
<!-- /emoji_list --></div>


<div class="footer clear">
<address>&copy; <a href="http://blockworks.jp/" target="_blank">blockworks</a>. all rights reserved.</address>
<p class="lang"><a href="http://emojisymbols.com/">en</a> <a href="http://emojisymbols.com/jp/">jp</a></p>
<!-- /footer --></div>


<!-- /cwrap --></div>
<script>
$(function(){
	$('.emoji_list input').on('click',function(){
		$(this).select();
	});
});
</script>
</body>
</html>